version : '3.3'

services:
    lb:
        image: haproxy
        ports:
            - 8080:8080
        volumes:
            - ./haproxy:/usr/local/etc/haproxy


    pg-rabbit-mongo-producer-1:
        image: pg-rabbit-mongo-producer
        ports:
          - 3101:3101
        environment:
            - APPID=producer-1
            - PORT=3101
            - DOCKER_HOST=host.docker.internal

    pg-rabbit-mongo-producer-2:
        image: pg-rabbit-mongo-producer
        ports:
          - 3102:3102
        environment:
            - APPID=producer-2
            - PORT=3102
            - DOCKER_HOST=host.docker.internal

    pg-rabbit-mongo-producer-3:
        image: pg-rabbit-mongo-producer
        ports:
            - 3103:3103
        environment:
            - APPID=producer-3
            - PORT=3103
            - DOCKER_HOST=host.docker.internal

    pg-rabbit-mongo-consumer1:
        image: pg-rabbit-mongo-consumer
        environment:
            - APPID=consumer-1
            - DOCKER_HOST=host.docker.internal

    pg-rabbit-mongo-consumer-2:
        image: pg-rabbit-mongo-consumer
        environment:
            - APPID=consumer-2
            - DOCKER_HOST=host.docker.internal

    pg-rabbit-mongo-consumer-3:
        image: pg-rabbit-mongo-consumer
        environment:
            - APPID=consumer-3
            - DOCKER_HOST=host.docker.internal
