version : '3'

services:
    lb:
        image: haproxy
        ports:
            - "8080:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
        network_mode: host

    pg-rabbit-mongo-producer-1:
        image: pg-rabbit-mongo-producer
        ports:
          - 3101:3101
        environment:
            - APPID=producer-1
            - PORT=3101
        network_mode: host

    pg-rabbit-mongo-producer-2:
        image: pg-rabbit-mongo-producer
        ports:
          - 3102:3102
        environment:
            - APPID=producer-2
            - PORT=3102
        network_mode: host

    pg-rabbit-mongo-producer-3:
        image: pg-rabbit-mongo-producer
        ports:
            - 3103:3103
        environment:
            - APPID=producer-3
            - PORT=3103
        network_mode: host

    pg-rabbit-mongo-consumer0:
        image: pg-rabbit-mongo-consumer
        environment:
            - APPID=consumer-0
        network_mode: host

    pg-rabbit-mongo-consumer-1:
        image: pg-rabbit-mongo-consumer
        environment:
            - APPID=consumer-1
        network_mode: host

    pg-rabbit-mongo-consumer-2:
        image: pg-rabbit-mongo-consumer
        environment:
            - APPID=consumer-2
        network_mode: host